# .github/workflows/azure-web-app-deploy.yml

name: Deploy Laravel-React App to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write # <<< THIS IS REQUIRED FOR OIDC AUTHENTICATION >>>

env:
  AZURE_WEBAPP_NAME: casecraft-app         # <<< IMPORTANT: REPLACE WITH YOUR AZURE APP SERVICE NAME >>>
  PHP_VERSION: '8.4'
  NODE_VERSION: '22' # Using Node 22

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # Authenticate using OIDC (OpenID Connect) with azure/login@v2
    - name: Azure Login
      uses: azure/login@v2 # <<< CHANGED TO v2 TO SUPPORT OIDC >>>
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        auth-type: OIDC # <<< Explicitly setting OIDC authentication type >>>
        # client-secret is NOT needed here for OIDC with v2/v3, as authentication happens via the OIDC token exchange
        # and the Federated Credential configuration in Azure AD.

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ env.PHP_VERSION }}
        extensions: pdo_sqlite, gd, exif, bcmath, mbstring
        tools: composer
        ini-values: post_max_size=100M, upload_max_filesize=100M

    - name: Install Composer Dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install Frontend Dependencies and Build
      run: |
        npm install
        npm run build

    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        package: .
